name: order_app
description: "Order of Monich."

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  provider: ^6.1.5+1
  http: ^1.6.0 # Если используется HTTP-клиент
  googleapis: ^15.0.0 # Для работы с Google API
  googleapis_auth: ^2.0.0 # Для аутентификации сервисных аккаунтов в Google
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  -  assets/images/bg1.webp
  -  assets/images/bg2.webp
  -  assets/images/bg3.webp
