name: order_app
description: "Order of Monich."

publish_to: "none" # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  camera: ^0.11.3
  charset_converter: ^2.3.0
  collection: ^1.19.1
  contacts_service: ^0.6.3
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  image: ^4.7.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  googleapis: ^15.0.0 # Для работы с Google API
  googleapis_auth: ^2.0.0 # Для аутентификации сервисных аккаунтов в Google
  http: ^1.6.0 # Если используется HTTP-клиент
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  table_calendar: ^3.2.0
  telephony: ^0.1.4 # для получения номера телефона (Android)

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/auth/
    - assets/images/products/
